#! /bin/sh
sxhkd &
numlockx on &

polybar example &
polybar md2 &

#feh --bg-fill ~/Pictures/wallpapers/gray.jpg &
back4.sh 0.010 ~/Pictures/wallpapers/train.gif &

compton --config ~/.config/compton/xd.conf &
/usr/bin/lxpolkit &
bspc monitor eDP -d I II III IV 
#bspc monitor eDP -d V VI VII VIII IX X
bspc monitor DisplayPort-0 -d V VI VII VIII IX X
xsetroot -cursor_name left_ptr
bspc config border_width 0
#bspc config active_border_color        "#E36B9F"
#bspc config normal_border_color        "#FFFFFF"
bspc config normal_border_color "#ae81ff"
bspc config active_border_color "#f66d9ef"
bspc config focused_border_color  "#e87d3e"
bspc config presel_feedback_color "#e6db74"
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
