#!/bin/bash
#
while true; do
    sleep 0.5
    TIME=$(playerctl metadata --format "{{mpris:length}}" | awk '{print int($1/1000000)}')
    IMG=$(playerctl metadata | grep "artUrl" | awk '{print $3}')
    echo $TIME
    echo $IMG
    feh -G $IMG &
    sleep $TIME
    kill $!
done


